services:
  # SERVICIO 1: BASE DE DATOS
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: muebles_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # SERVICIO 2: TU APP JAVA
  app:
    build: .
    restart: always
    ports:
      - "8086:8086"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/muebles_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: